name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install deprendencies
      run: sudo apt-get install -y rename
    - name: Run a one-line script
      run: make -B
