name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install deprendencies
      run: sudo apt-get install -y rename
    - name: Make pdf
      run: make -B
    - name: Upload pdf
      uses: actions/upload-artifact@v1
      with:
        name: circllhist.pdf
        path: ./circllhist.pdf
